# Generated by Django 5.1.4 on 2024-12-23 16:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("medecin", "Médecin"),
                            ("infermier", "Infirmier"),
                            ("pharmacien", "Pharmacien Hospitalier"),
                            ("laborantin", "Laborantin"),
                            ("radiologue", "Radiologue"),
                            ("admin", "Administrateur"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="CentreHospitalier",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=255)),
                ("place", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="DossierMedical",
            fields=[
                (
                    "dossierID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("createdAt", models.DateField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
                ("qrCode", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Infermier",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("jour", "Jour"),
                            ("nuit", "Nuit"),
                            ("rotation", "Rotation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "specialite",
                    models.CharField(
                        choices=[
                            ("generale", "Générale"),
                            ("chirurgie", "Chirurgie"),
                            ("pediatrie", "Pédiatrie"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("telephone", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Laboratin",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("jour", "Jour"),
                            ("nuit", "Nuit"),
                            ("rotation", "Rotation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "specialite",
                    models.CharField(
                        choices=[
                            ("biochimie", "Biochimie"),
                            ("hematologie", "Hématologie"),
                            ("microbiologie", "Microbiologie"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("telephone", models.CharField(max_length=20)),
                ("nombreTests", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Medecin",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specialite",
                    models.CharField(
                        choices=[
                            ("generaliste", "Généraliste"),
                            ("cardiologue", "Cardiologue"),
                            ("chirurgien", "Chirurgien"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("telephone", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="PharmacienHospitalier",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("jour", "Jour"),
                            ("nuit", "Nuit"),
                            ("rotation", "Rotation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("telephone", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Radiologue",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("jour", "Jour"),
                            ("nuit", "Nuit"),
                            ("rotation", "Rotation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "specialite",
                    models.CharField(
                        choices=[
                            ("radiographie", "Radiographie"),
                            ("echographie", "Échographie"),
                            ("scanner", "Scanner"),
                            ("irm", "IRM"),
                        ],
                        max_length=20,
                    ),
                ),
                ("telephone", models.CharField(max_length=20)),
                ("nombreTests", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="centreHospitalier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="healthhub_back.centrehospitalier",
            ),
        ),
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "consultationID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("dateConsultation", models.DateField()),
                ("diagnostic", models.TextField()),
                ("resume", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planifie", "Planifiée"),
                            ("en_cours", "En Cours"),
                            ("termine", "Terminée"),
                            ("annule", "Annulée"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthhub_back.dossiermedical",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActiviteInfermier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "typeActivite",
                    models.CharField(
                        choices=[
                            (
                                "administration_medicament",
                                "Administration de Médicament",
                            ),
                            ("soins", "Soins"),
                            ("observation", "Observation"),
                            ("prelevement", "Prélèvement"),
                            ("autre", "Autre"),
                        ],
                        max_length=50,
                    ),
                ),
                ("details", models.TextField()),
                ("createdAt", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planifie", "Planifiée"),
                            ("en_cours", "En Cours"),
                            ("termine", "Terminée"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthhub_back.dossiermedical",
                    ),
                ),
                (
                    "infermier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthhub_back.infermier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Medicament",
            fields=[
                (
                    "medicamentID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("comprime", "Comprimé"),
                            ("sirop", "Sirop"),
                            ("injection", "Injection"),
                            ("pommade", "Pommade"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
            ],
            options={
                "unique_together": {("nom", "type")},
            },
        ),
        migrations.CreateModel(
            name="Ordonnance",
            fields=[
                (
                    "ordonnanceID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("valide", models.BooleanField(default=True)),
                ("dateCreation", models.DateField(auto_now_add=True)),
                ("dateExpiration", models.DateField()),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthhub_back.consultation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NurseMedication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("administeredAt", models.DateTimeField(blank=True, null=True)),
                (
                    "dosage",
                    models.CharField(
                        choices=[
                            ("faible", "Faible"),
                            ("moyen", "Moyen"),
                            ("fort", "Fort"),
                        ],
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planifie", "Planifiée"),
                            ("administre", "Administrée"),
                            ("reporte", "Reportée"),
                            ("annule", "Annulée"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "nurseActivite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthhub_back.activiteinfermier",
                    ),
                ),
                (
                    "ordonnance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthhub_back.ordonnance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrdonnanceMedicament",
            fields=[
                (
                    "ordonnanceMedicamentID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("duree", models.CharField(max_length=50)),
                (
                    "dosage",
                    models.CharField(
                        choices=[
                            ("faible", "Faible"),
                            ("moyen", "Moyen"),
                            ("fort", "Fort"),
                        ],
                        max_length=10,
                    ),
                ),
                ("frequence", models.CharField(max_length=50)),
                ("instructions", models.TextField()),
                (
                    "med",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthhub_back.medicament",
                    ),
                ),
                (
                    "ordonnance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthhub_back.ordonnance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "patientID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("NSS", models.BigIntegerField(unique=True)),
                ("nom", models.CharField(max_length=255)),
                ("prenom", models.CharField(max_length=255)),
                ("dateNaissance", models.DateField()),
                ("adresse", models.CharField(max_length=255)),
                ("telephone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("mutuelle", models.CharField(max_length=255)),
                ("contactUrgence", models.CharField(max_length=255)),
                ("createdAt", models.DateField(auto_now_add=True)),
                ("password", models.CharField(max_length=128)),
                (
                    "centreHospitalier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthhub_back.centrehospitalier",
                    ),
                ),
                (
                    "medecin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="healthhub_back.medecin",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Facture",
            fields=[
                (
                    "factureID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("montant", models.FloatField()),
                ("description", models.CharField(max_length=255)),
                ("createdAt", models.DateField(auto_now_add=True)),
                ("datePaiement", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("en_attente", "En Attente"),
                            ("paye", "Payée"),
                            ("annule", "Annulée"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "methodePaiement",
                    models.CharField(
                        choices=[
                            ("carte", "Carte"),
                            ("especes", "Espèces"),
                            ("cheque", "Chèque"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "centreHospitalier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthhub_back.centrehospitalier",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthhub_back.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Examen",
            fields=[
                (
                    "examenID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("labo", "Laboratoire"),
                            ("radio", "Radiologie"),
                            ("scanner", "Scanner"),
                            ("irm", "IRM"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("createdAt", models.DateField(auto_now_add=True)),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("planifie", "Planifié"),
                            ("en_cours", "En Cours"),
                            ("termine", "Terminé"),
                            ("annule", "Annulé"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("urgent", "Urgent"),
                            ("tres_urgent", "Très Urgent"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthhub_back.consultation",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthhub_back.patient",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dossiermedical",
            name="patient",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="healthhub_back.patient"
            ),
        ),
        migrations.CreateModel(
            name="ResultatLabo",
            fields=[
                (
                    "resLaboID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("resultat", models.TextField()),
                ("dateAnalyse", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("en_cours", "En Cours"),
                            ("termine", "Terminé"),
                            ("valide", "Validé"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "examen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthhub_back.examen",
                    ),
                ),
                (
                    "laboratin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthhub_back.laboratin",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HealthMetrics",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("medical_record_id", models.IntegerField()),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("temperature", "Température"),
                            ("pression_arterielle", "Pression Artérielle"),
                            ("glycemie", "Glycémie"),
                            ("autre", "Autre"),
                        ],
                        max_length=30,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit", models.CharField(max_length=50)),
                ("measured_at", models.DateTimeField(auto_now_add=True)),
                ("recorded_by", models.IntegerField()),
                (
                    "resLabo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="healthhub_back.resultatlabo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResultatRadio",
            fields=[
                (
                    "resRadioID",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("radioImgURL", models.URLField(max_length=500)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("radiographie", "Radiographie"),
                            ("echographie", "Échographie"),
                            ("scanner", "Scanner"),
                            ("irm", "IRM"),
                        ],
                        max_length=20,
                    ),
                ),
                ("rapport", models.TextField()),
                ("dateRealisation", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("en_cours", "En Cours"),
                            ("termine", "Terminé"),
                            ("valide", "Validé"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "examen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthhub_back.examen",
                    ),
                ),
                (
                    "radiologue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="healthhub_back.radiologue",
                    ),
                ),
            ],
        ),
    ]
